DEploid-dev/DEploid

src/export/pfDeconvIOExport.cpp
src/mcmc.cpp
src/pfDeconvIO.cpp
src/pfDeconvIO.hpp
tests/testForbidMoves.sh
tests/unittest/test_pfDeconvIO.cpp

update forbid moves

---

src/exceptions.hpp
src/export/pfDeconvIOExport.cpp
src/mcmc.cpp
src/pfDeconvIO.cpp
src/pfDeconvIO.hpp
tests/testForbidMoves.sh
tests/unittest/test_pfDeconvIO.cpp

initial changes to include initial proportions

---

src/exceptions.hpp
src/export/pfDeconvIOExportPosteriorProb.cpp
src/mcmc.cpp
src/pfDeconvIO.cpp
src/pfDeconvIO.hpp
src/updateHap.cpp
tests/testPOS.sh
tests/unittest/test_pfDeconvIO.cpp
utilities/makePlots2.r
utilities/makePlots4.r

update print post prob, fixing index of recomb probabilities

---

.travis.yml
Makefile.am
src/dEploidIO.cpp

use sed -i'.bak' -e

---

.travis.yml
circle.yml
src/dEploid.cpp
src/mcmc.cpp
src/random/mersenne_twister.cpp
src/random/mersenne_twister.hpp
src/random/random_generator.hpp
tests/test_binaryReproducible.sh
tests/unittest/test_mcmc.cpp
tests/unittest/test_updatePairHap.cpp
tests/unittest/test_updateSingleHap.cpp
tests/unittest/test_utilities.cpp

and include tests for reproduciable code

Use smart pointer

---

.travis.yml
circle.yml
src/codeCogs/mersenne.hpp
src/codeCogs/randomSample.hpp
src/mcmc.cpp
src/mcmc.hpp
src/random/random_generator.hpp
tests/unittest/test_mcmc.cpp
version

fixing portability issue across platforms

Random number generator

---

src/dEploidIO.cpp
src/dEploidIO.hpp
src/export/dEploidIOExport.cpp
src/mcmc.cpp
src/mcmc.hpp
utilities/dEploidTools.r
utilities/interpretDEploid.r

plot last iteration of ibd segment

Ibd recomb

---

utilities/DEploidR.R
utilities/dEploidTools.r

implement plot, close #208

---

src/dEploidIO.hpp
src/export/dEploidIOExport.cpp
src/mcmc.cpp
src/mcmc.hpp

```
MCMC step 100% completed.
##########################################
##########################################
Program was compiled on: Mon--8-May-08:15:25-UTC-2017
dEploid version: 8dad48b16b4a72c5bc3090aaacdac5eaa55d1be2
Input data: 
Panel: labStrains.14.panel.txt
PLAF: ../labStrains.14.PLAF.txt
VCF: ../PG0389-C.14.vcf
Exclude: exclude.14.txt
MCMC parameters: 
MCMC burn: 0.5
MCMC sample: 800
MCMC sample rate: 5
Random seed: 3
Update Prop: YES
Update Single: YES
Update Pair: YES
Other parameters:
Miss copy prob: 0.01
Avrg Cent Morgan: 15000
Ne: 10
ScalingFactor: 100
MCMC diagnostic:
Max_llks: -42186.9
Mean_theta_llks: -41592.5
Mean_llks: -41602.7
Stdv_llks: 17.833
DIC_by_Dtheta: 83225.6
DIC_by_varD: 83841.4
Run time:
Start at: Mon May  8 15:30:28 2017
End at: Mon May  8 15:31:21 …
```

compute diagnostics

---

src/dEploidIO.cpp
utilities/dEploidTools.r
utilities/interpretDEploid.r

plot posterior probabilities in a ring

---

.circleci-matrix.yml
ci/.circleci-matrix.yml
circle.yml

generate a short git url
```bash
curl -i https://git.io -F "url=https://raw.githubusercontent.com/shajoezhu/circleci-matrix/master/src/install.sh"
```
Note in the line
#!/usr/bin/env bash
set -e
mkdir -p ~/.local/bin
curl \
--fail\
--silent \
--show-error \
--location \
https://raw.githubusercontent.com/michaelcontento/circleci-matrix/master/src/circleci-matrix.sh \
-o ~/.local/bin/circleci-matrix
chmod +x ~/.local/bin/circleci-matrix
change michaelcontento to shajoezhu, if the original file does not exist anymore

setup circle ci, and use containers to compile deploid with different compilers

---

src/dEploid.cpp
src/dEploidIO.cpp
src/dEploidIO.hpp
src/export/dEploidIOExport.cpp
src/ibd.cpp
src/ibd.hpp
src/mcmc.cpp
src/mcmc.hpp
utilities/dEploidTools.r
utilities/interpretDEploid.r

1. compute ibd probabilities only on the effective haplotypes
2. change default number of strains to 4. 5 is not necessary
3. update plotting interpretation utilities

Improve ibd

---

utilities/dEploidTools.r

zoom in to chrom 1, the very last three positions

modify color for wsaf vs idx

---

src/dEploid.cpp
src/dEploidIO.cpp
src/dEploidIO.hpp
src/export/dEploidIOExport.cpp
src/ibd.cpp
src/ibd.hpp
src/panel.cpp

see #250 
implementing, taking max at forward posterior probabilities and encode to viterbi state

implement viterbi encoding

---

.travis.yml
bootstrap
checkfiles.sh

Created git tags for submodules, 
bootstrap will trigger check files, depends on how files are cloned or zip downloaded. It will update submodules accordingly

resolve #309

---

src/mcmc.cpp
src/panel.cpp
src/txtReader.cpp
src/updateHap.cpp
src/vcfReader.cpp

making changes in deploid-r

---

src/dEploidIO.cpp
tests/unittest/test_dEploidIO.cpp

update, close #322

---

src/dEploidIO.cpp
tests/unittest/test_dEploidIO.cpp

close #321

---

src/dEploidIO.cpp

close #318

---

src/dEploidIO.cpp
src/txtReader.cpp

close #150

---

src/dEploidIO.cpp
tests/unittest/test_dEploidIO.cpp

close #327

---

src/dEploidIO.cpp
src/dEploidIO.hpp
src/vcfReader.cpp
src/vcfReader.hpp
tests/unittest/test_dEploidIO.cpp

close #142

---

.ci/checkedList
.ci/mycppfileList
src/panel.cpp
src/panel.hpp
src/utility.cpp
src/utility.hpp

check style

---

Makefile.am
README.md
configure.ac
dEploid_completion.sh

Auto complete

---

src/dEploidIO-workflow.cpp
src/mcmc.cpp

fixing proportion dont add to 1

---

.ci/checkedList
src/dEploidIO-operation.cpp
src/dEploidIO-workflow.cpp
src/dEploidIO.cpp
src/dEploidIO.hpp
src/export/dEploidIOExport.cpp
src/export/dEploidIOExportPosteriorProb.cpp
src/export/writeMcmcRelated.cpp
src/ibd.cpp
src/mcmc.cpp
src/param.hpp
tests/unittest/test_dEploidIO.cpp
tests/unittest/test_ibd.cpp
tests/unittest/test_mcmc.cpp

Issue338 param

---

Makefile.am
tests/unittest/test_workflow.cpp

Adding workflow unittest

---

.github/workflows/ccpp.yml
tests/test-coverage-coverall.sh

turn off run
testing
testing
update
update
update

adding to coverall

---

Makefile.am
src/debug/mcmcDebug.cpp
src/ibd.cpp
src/log-double.hpp
src/logsum.hpp
src/mcmc.cpp
src/mcmc.hpp
src/updateHap.cpp
src/updateHap.hpp
src/utility.cpp
src/utility.hpp
tests/unittest/test_mcmc.cpp
tests/unittest/test_updateSingleHap.cpp
tests/unittest/test_utilities.cpp

This branch introduces the `log_double_t` type and uses it in a few places.

Log double t

---

src/mcmc.cpp
src/mcmc.hpp
src/utility.cpp
tests/unittest/test_utilities.cpp

Can you look over this PR?  I think it works fine, but you might want to put some of the code in a different place.
It does two things:
1. Compute the likelihoods with the normalizing constant. (This is so I could check that they were correct.)
2. Write out an MCMC trace.  (This is the check how the chain is mixing.)
The trace easily allows you to see the distribution of K, and also the distribution of the weights.
The trace file can be viewed with Tracer (http://tree.bio.ed.ac.uk/software/tracer/).

Check mcmc

---

.github/workflows/ccpp.yml
src/dEploidIO.cpp
src/dEploidIO.hpp

expose randomseed

---

.github/workflows/ccpp.yml

Rversion update

---

.github/workflows/ccpp.yml
Makefile.am
src/param.hpp
tests/test-coverage-coverall.sh

resolve #375
